# Generated by Django 5.2.5 on 2025-09-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
